Home design unfinish
luislealdev/itcoders.tech pull request #9
Opened 2024-03-07 00:37 UTC by Alfred024

Hola, aún no he terminado, ni tiene responsive, y cree varios  archivos que no están bien estructurados, pero se ve el diseño de lo que sería el Home. Mañana le sigo.

2024-03-07 17:28 UTC, luislealdev commented on src/app/globals.css
> +  box-sizing: border-box;
Delete this box-sizing please, if you use it you can create a class.

2024-03-07 17:29 UTC, luislealdev commented on src/app/globals.css
> +.justify-between{
This class already exists in leal styles, you don't need it here.

2024-03-07 17:29 UTC, luislealdev commented on src/app/globals.css
> +.width-100{
This class already exists in leal-styles, delete it

2024-03-07 17:30 UTC, luislealdev commented on src/app/globals.css
> +.padding-container{
This padding container is a class that can be replaced for p-10 (For padding with 10px) in leal-styles.

2024-03-07 17:31 UTC, luislealdev commented on src/app/globals.css
> +.border-radius-10{
This is a class that already exists in leal-styles with "radius"

2024-03-07 17:31 UTC, luislealdev commented on src/app/globals.css
> +.border-radius-30{
This is a class that already exists in leal-styles with "radius-30", also name says 30 but value is 40.

2024-03-07 17:32 UTC, luislealdev commented on src/app/globals.css
> +.Span-Section{
This class only contains one atribute (space-between), it an be replaced with class space-between in leal-styles

2024-03-07 17:34 UTC, luislealdev commented on src/app/page.tsx
> +          <div className="border-radius-30 p-10 bg-light-gray-color flex  align-center" style={{width: "180px", height:"75px"}}>
Try not to use fiex widths and heights, it is necessary in some cases but it is not good for automatic responsive.

2024-03-07 17:35 UTC, luislealdev commented on src/components/project-card/ProjectCard.css
> +/* .Project-Card{
Be carefull with static heights

2024-03-07 17:36 UTC, luislealdev requested changes
Hi, in the code i leave you some comments, if you can fixed this things it would be good. <3

2024-03-08 03:15 UTC, Alfred024 commented
I fixed the issues in the CSS.

2024-03-12 02:04 UTC, merged